---
apiVersion: v1
kind: Service
metadata:
    name: pingpong-api-service
spec:
    selector:
        app: pingpong-api
    ports:
        - protocol: 'TCP' # lista de informações da porta.
          port: 2222
          targetPort: 2222
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pingpong-api
spec:
    replicas: 3
    selector:
        matchLabels:
            app: pingpong-api
    template:
        metadata:
            labels:
                app: pingpong-api
        spec:
            containers:
                - name: pingpong
                  image: joaopfsiqueira/pingpong-kubernetes-api
